
test_and_build:
  image:  teracy/ubuntu:18.04-dind-latest

  stage: build
  tags:
   - linux 
   
  script: 
   - docker
   - pwd
   - docker login snapsearch.azurecr.io -u snapsearch -p 2s601MKAF38sPdCAa/xUHLWG2kiutfp7
   - docker build -t $CI_REGISTRY_IMAGE .
   - docker push  $CI_REGISTRY_IMAGE


