test_and_build:
  image: docker:latest
  before_script:
    - docker login -u "abudimo" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  stage: build
  tags: 
    - Docker  
  script:
    - cd snap_search/backend/image_embeddings
    - docker build -t abudimo/snapsearch:latest .
    - docker push abudimo/snapsearch:latest

    


