test_and_build:
  image: docker:latest
  stage: build
  services:
    - abudimo/snapsearch:latest
  tags: 
    - Docker
  script:
    - cd snap_search/backend/image_embeddings
    - docker build -t abudimo/snapsearch:latest .
    - docker push abudimo/snapsearch:latest

    


