#!/usr/bin/env bash


IMAGE_SHA=$(docker inspect --format='{{ index .RepoDigests 0}}' snapsearch.azurecr.io/snapsearch:latest)
echo "${IMAGE_SHA}"
az login service-priciple --username --password --tenant
az webapp config container set --docker-custom-image-name ${IMAGE_SHA} \
    --docker-registry-server-password +4ybRTZ6aX0B8wcB4VM10KpxCuTpyRrE \
    --docker-registry-server-url https://snapsearch.azurecr.io \
    --docker-registry-server-user snapsearch \
    --name snapsearch  \
    --resource-group snapsearch9